name: C++ Lint & Naming Convention Check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install clang tools
      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      # 3. Run clang-tidy on C++ files
      - name: Run clang-tidy
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-tidy --warnings-as-errors=* --quiet
