name: Unreal Naming Convention Check

on:
  pull_request:
    branches: [ main ]

jobs:
  naming-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run naming convention check
        run: |
          python3 check_naming.py TheScaleWeShare/Source
